.PHONY: all my_scalar find_bits clean

all: my_scalar find_bits clean

my_scalar:
	gcc my_scalar/my_scalar.c -o my_scalar/my_scalar -Wall -ansi -std=c90 -pedantic

find_bits:
	gcc find_bits/find_bits.c -o find_bits/find_bits -Wall -ansi -std=c90 -pedantic

clean:
	@echo "Done ...\n"