.PHONY: all

all: lists_c my_and clean

lists_c: lists_c.c
	gcc lists_c.c -o lists_c -Wall -ansi -std=c90 -pedantic

my_and: my_and.c
	gcc my_and.c -o my_and -Wall -ansi -std=c90 -pedantic

clean:
	@echo "Done ...\n"